# Generated by Django 4.2 on 2023-04-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listhive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='trackerfield',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
