# Generated by Django 4.2 on 2023-04-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listhive', '0002_folder_trackerinfolder_listinfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
