# Generated by Django 4.2 on 2023-04-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listhive', '0003_alter_list_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
