# Generated by Django 4.2 on 2023-04-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listhive', '0004_alter_list_description_alter_tracker_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trackeritemvalue',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
